# Generated by Django 6.0.1 on 2026-04-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_producto_campos_inventario_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('pago_movil', 'Pago móvil')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('ajuste', 'Ajuste'), ('salida_venta', 'Salida por venta')], default='entrada', max_length=20),
        ),
    ]
