# Generated by Django 6.0.1 on 2026-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_estado_pago_venta_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
