# Generated by Django 6.0.1 on 2026-04-23 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cliente_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_dolar', models.DecimalField(decimal_places=2, default=Decimal('483.76'), max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración fiscal',
                'verbose_name_plural': 'Configuraciones fiscales',
                'ordering': ['-activa', '-actualizado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_porcentaje_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tasa_dolar_aplicada',
            field=models.DecimalField(decimal_places=2, default=Decimal('483.76'), max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
