from django.urls import path
from .views import (
    ClienteCreateView,
    ClienteDeleteView,
    ClienteDetailView,
    ClienteListView,
    ClienteUpdateView,
    DashboardTemplateView,
    HomeView,
    ProductoAgotadoListView,
    ProductoCreateView,
    ProductoDeleteView,
    ProductoDetailView,
    ProductoListView,
    ProductoPrecioUpdateView,
    ProductoStockUpdateView,
    ProductoUpdateView,
    RegistroTemplateView,
    ReporteQuincenalView,
    UsersTemplateView,
    VentaCreateView,
    VentaDetailView,
    VentaListView,
    VentaPagoView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', DashboardTemplateView.as_view(), name='dashboard'),
    path('registro/', RegistroTemplateView.as_view(), name='registro'),
    path('users/', UsersTemplateView.as_view(), name='users'),
    path('clientes/', ClienteListView.as_view(), name='cliente_list'),
    path('clientes/<int:pk>/', ClienteDetailView.as_view(), name='cliente_detail'),
    path('clientes/crear/', ClienteCreateView.as_view(), name='cliente_create'),
    path('clientes/<int:pk>/editar/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('clientes/<int:pk>/eliminar/', ClienteDeleteView.as_view(), name='cliente_delete'),
    path('productos/', ProductoListView.as_view(), name='producto_list'),
    path('productos/agotados/', ProductoAgotadoListView.as_view(), name='producto_agotados'),
    path('productos/crear/', ProductoCreateView.as_view(), name='producto_create'),
    path('productos/stock/', ProductoStockUpdateView.as_view(), name='producto_stock'),
    path('productos/<int:pk>/', ProductoDetailView.as_view(), name='producto_detail'),
    path('productos/<int:pk>/precio/', ProductoPrecioUpdateView.as_view(), name='producto_price_update'),
    path('productos/<int:pk>/editar/', ProductoUpdateView.as_view(), name='producto_update'),
    path('productos/<int:pk>/eliminar/', ProductoDeleteView.as_view(), name='producto_delete'),
    path('ventas/', VentaListView.as_view(), name='venta_list'),
    path('ventas/crear/', VentaCreateView.as_view(), name='venta_create'),
    path('ventas/pago/', VentaPagoView.as_view(), name='venta_pago'),
    path('ventas/<int:pk>/', VentaDetailView.as_view(), name='venta_detail'),
    path('reportes/quincenal/', ReporteQuincenalView.as_view(), name='reporte_quincenal'),
]
